---
- name: Install Audit Pre Reqs - RedHat
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ redhat_packages }}"
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }}"

- name: Install Audit Packages - Debian
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ debian_packages }}"
  when: "ansible_os_family | lower == 'debian' and {{ enable_audit }}"

- name: create audit-directory if it does not exist
  file: path='/etc/audit' owner=root group=root mode=0755 state=directory

- name: create auditd configuration
  template: src='auditd.j2' dest='/etc/audit/auditd.conf' owner=root group=root mode=0440

- name: create rules-directory if it does not exist
  file: path='/etc/audit/rules' owner=root group=root mode=0755 state=directory
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }} and ansible_distribution_version <= '6.8'"

- name: create sane rules
  template: src='audit.rules.j2' dest='/etc/audit/rules/audit.rules' owner=root group=root mode=0440
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }} and ansible_distribution_version <= '6.8'"

- name: create rules-directory if it does not exist
  file: path='/etc/audit/rules.d' owner=root group=root mode=0755 state=directory
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }} and ansible_distribution_version >= '7'"

- name: create sane rules
  template: src='audit.rules.j2' dest='/etc/audit/rules.d/audit.rules' owner=root group=root mode=0440
  when: "ansible_os_family | lower == 'redhat' and {{ enable_audit }} and ansible_distribution_version >= '7'"

- name: create sane rules
  template: src='audit.rules.j2' dest='/etc/audit/audit.rules' owner=root group=root mode=0440
  when: "ansible_os_family | lower == 'debian' and {{ enable_audit }}"

- name: Make sure auditd server is running
  service:
    name: auditd
    state: started
    enabled: yes
